### ISSUE TITLE
MinIO等のS3互換実装からの接続をする場合に変更が必要そう

### ISSUE THREAD

**Issue by fono09** [totegamma/cc-media-server#1]
https://github.com/totegamma/cc-media-server/blob/26e88b2f7408f079e83d7bde2cd2e12b2a4c1c91/main.go#L94

https://rennnosukesann.hatenablog.com/entry/2021/11/22/112925 の例

```golang
 endpoint := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
        return aws.Endpoint{
            URL: "http://localhost:9000",
        }, nil
    })
```

aws.EndpointのURLをいい感じに環境変数から設定できる必要ありそうです。

破壊的変更を避ける場合 `os.Getenv("accountId")` をR2のアカウントIDとして解釈する、
なければ、 `os.Getenv("endpointUrl")` を求め使い、それもなければコケる、というのが破壊的変更のない落とし所ですかね。

この規模なら、方針違いで捨て前提のPRまでやっちゃうんですが
ちょっと時間が時間なのでIssueで残しておきます。

相互リンク: totegamma/concurrent-square#3

**Comment by totegamma** [comment]
設定が変わるだけで既存のDBデータのマイグレは必要なさそう？
とはいえ使ってる人も少ないのでバシバシベストな方向に変更しちゃう方針で行こうと思います！

**Comment by fono09** [comment]
実際にMinIOをやってみたらものすごいスコープが広がってしまった 😇
